### ISSUE TITLE
Hang while extracting the deployed contract code

### ISSUE THREAD

**Issue by sunbeomso** [nescio007/teether#14]
The fix  https://github.com/nescio007/teether/commit/409cee9feb2df9a6a093a813e66532660acd6f7d does not work for the contract below that I mentioned in https://github.com/nescio007/teether/issues/13:

https://etherscan.io/address/0xead71f4d060ddc7656c959b482fbdfaca95c5d9d#code

I have rebuilt teEther after ``git pull`` for your new fix, but now teEther hangs when trying to extract the deployed code for the contract above.

**Comment by nescio007** [comment]
Thanks, yes, the previous fix did indeed create an infinite loop that kept exploring the same basic blocks over and over again :slightly_frowning_face: 
For historic reasons, CFG exploration used a different method here than in the rest of the project. c1a8d15 removes that duplicate method, which should eliminate the hang, but still work for the contracts reported in #13.
Thanks again!
