### ISSUE TITLE
"No CODECOPY in this contract" & "Could not find contract code" error

### ISSUE THREAD

**Issue by jefferson78** [nescio007/teether#16]
Hi

Could you please help me figure out the error that is returned by extract_contract_code.py

I have tried to run couple of contracts' bytecode with extract_contract_code.py and all the time getting
WARNING:root:No CODECOPY in this contract!!
ERROR:root:Could not find contract code

I have looked into code of extract_contract_code.py

if b'\x39' not in code:
        logging.warning('No CODECOPY in this contract!!')
    contract = extract_contract_code(code)
    if contract:
        print(contract.hex())
    else:
        logging.error('Could not find contract code')

Could you please explain what does this 'if b'\x39' not in code' statement check.
What can be the reason that contract bytecode returns 'No CODECOPY in this contract' and 'Could not find contract code' ?

Thank you for your time

--
here are some examples:
https://etherscan.io/address/0x19f8ae8eb968d2eddcf2441ee1ba8f74dcf9aa67
python3 extract_contract_code.py contract.code
WARNING:root:No CODECOPY in this contract!!
ERROR:root:Could not find contract code

https://etherscan.io/address/0x822f25dbdec2a70086db81482cea4b1b757dbd14
python3 extract_contract_code.py contract.code
ERROR:root:Could not find contract code

**Comment by nescio007** [comment]
Hi,

the `extract_contract_code.py` script is there to extract the *actual* contract code from the contract *creation* code that you can e.g. find on etherscan (or that will be produced by `solc`). This contract *creation* code usually performs some computation and then uses the `CODECOPY` instruction (opcode `0x39`) to write the *actual* contract code.
This is why `extract_contract_code.py` checks for `b'\x39' not in code` -- if there is no `CODECOPY` instruction, then the provided code most likely isn't a contract creation code.

The contents of `contract.code` should therefore be the (hex-encoded) contract creation code. E.g., for https://etherscan.io/address/0x19f8ae8eb968d2eddcf2441ee1ba8f74dcf9aa67, `contract.code` should start off like this:
```
60806040526040805190810160405280600c81526020017f50726564696374546f6b656e000000000000000000000000000000000000000081525060049080519060200190620000519291906200018d565b506040805190810160405280600281526020017f5...
```

**Comment by jefferson78** [comment]
Hey

Thank you for response and explanations.
Yes, if we take, for example, https://etherscan.io/address/0x19f8ae8eb968d2eddcf2441ee1ba8f74dcf9aa67 it will have code as you mentioned.
But then when I run python3 extract_contract_code.py contract.code where contract.code contains'60806040526040805190810160405280600c81526020017f50726564696374546f6b656e00...'
it returns
WARNING:root:No CODECOPY in this contract!!
ERROR:root:Could not find contract code

Then not sure why it can be so. Maybe you have some suggestions?

p.s. in this particular example I simply triggered eth_getCode rpc call to fetch contract code for 0x19f8ae8eb968d2eddcf2441ee1ba8f74dcf9aa67

Thank you for your time


UPDATE:
I see that creation code on etherscan is not the same as the one returned by eth_getCode. so that can be a problem in my case.
However,
i took creation code manually from etherscan for https://etherscan.io/address/0x19f8ae8eb968d2eddcf2441ee1ba8f74dcf9aa67 and run extract_contract_code.py and it returns 
```
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:Jump to invalid address
WARNING:root:bytearray(b'`\x80`@.........
```

and not generating actual contract code.

Could you please check on your side if this is a problem on my side or simply teether currently cannot process this creation code.

Thank you

**Comment by nescio007** [comment]
Hm, I cannot reproduce the problem.
I've just installed teether in a fresh Ubuntu 20.04 VM, and ran `extract_contract_code.py` on [contract.code](https://github.com/nescio007/teether/files/5590182/contract.code.txt). You will see a few warnings for `Jump to invalid address` (which happens because older `solc` versions created illegal jumps to trigger an exception), but afterwards it outputs [extracted_contract.code](https://github.com/nescio007/teether/files/5590184/extracted_contract.code.txt) (well, technically it prints it to `stdout`).

Anyway, if you're able to obtain the actual contract code from `eth_getCode`, you may as well skip the extraction step and continue from there.

**Comment by jefferson78** [comment]
Thank you.
I will then investigate on my side.

Then closing this 'issue'.
