### ISSUE TITLE
Which version of solidity and python do you use?

### ISSUE THREAD

**Issue by ZeroGold52** [nescio007/teether#17]
I deployed teether on my Ubuntu 16.04 machine with solidity v0.4.0 and v0.4.24, but failed to compile test.sol to test.code.
The error information is as follows:

`test.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.0-develop.2020.12.04+commit.acd334c9.Linux.g++ - note that nightly builds are considered to be strictly less than the released version`

**Comment by nescio007** [comment]
Hi,

## Solidity
I believe we were using solc v0.4.9, but any 0.4.x (with x>=9) should work. It appears you were using a **development version** of v0.4.0, which, according to the error message, is `strictly less than 0.4.0`.

## Python
teEther uses python3

**Comment by ZeroGold52** [comment]
> Hi,
> 
> ## Solidity
> I believe we were using solc v0.4.9, but any 0.4.x (with x>=9) should work. It appears you were using a **development version** of v0.4.0, which, according to the error message, is `strictly less than 0.4.0`.
> 
> ## Python
> teEther uses python3

Got it~Thanks.
