### ISSUE TITLE
No module named teether.cfg.cfg

### ISSUE THREAD

**Issue by xpao24** [nescio007/teether#4]
python bin/extract_contract_code.py test.code > test.contract.code

Traceback (most recent call last):
  File "bin/extract_contract_code.py", line 5, in <module>
    from teether.cfg.cfg import CFG
ImportError: No module named teether.cfg.cfg

**Comment by nescio007** [comment]
Hi, thanks for your issue.
All scripts assume that the teether package is installed in the python path (using e.g. python setup.py install).
I have updated the readme accordingly
