### ISSUE TITLE
TypeError: '>=' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by knight2008** [nescio007/teether#6]
I copy the hex code from etherscan.
https://etherscan.io/address/0xf7f69b431c5fdc18d99248498386e72418791433#code
Paste the hex to the file evmcode.hex, but run error. 

python bin/extract_contract_code.py  evmcode.hex 
Traceback (most recent call last):
  File "bin/extract_contract_code.py", line 50, in <module>
    contract = extract_contract_code(code)
  File "bin/extract_contract_code.py", line 19, in extract_contract_code
    icfg = CFG(generate_BBs_recursive(code), fix_xrefs=True)
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/site-packages/teether-0.1.1-py3.7.egg/teether/cfg/disassembly.py", line 71, in generate_BBs_recursive
TypeError: '>=' not supported between instances of 'tuple' and 'int'

**Comment by knight2008** [comment]
could you help to check what's wrong?

**Comment by nescio007** [comment]
Thanks for reporting, fixed in 97d4fc74ca4d93747fb9a758e1b36692cf465ff4

On another note: it appears that etherscan.io sometimes already displays the extracted code (as in your case). In these cases it is not necessary to run `extract_contract_code` first.

**Comment by knight2008** [comment]
so the code I used is extracted code? 
and another question: what is the difference between original code and extracted code? 
Thanks a lot.

**Comment by nescio007** [comment]
The code used to deploy a new contract (i.e. the one output by `solc`) contains not only the contract itself, but also some additional code to create the new contract. It is essentially a contract that creates your new contract. (= "original code")

The `extract_contract_code` script takes this contract-creating-contract and extracts only the code of the contract that will be created. (="extracted code")

I haven't yet figured out when etherscan.io shows the original code, and when it shows the extracted code.

**Comment by knight2008** [comment]
okay. So what kind of the hex code if I compile my code with remix online ?

**Comment by nescio007** [comment]
Afaik remix outputs whatever `solc` would output, i.e., a contract-creating-contract.
