### ISSUE TITLE
❯ ERROR:root:Could not find contract code

### ISSUE THREAD

**Issue by ToolmanInside** [nescio007/teether#8]
I tried input a bytecode file but got this error:
`ERROR:root:Could not find contract code`

I have checked your implementations. In my inspections, I found an issue in the part of handling input bytecode. 

In file `teether/cfg/disassembly.py`, we have such a function `generate_BBs_recursive`:
```Python
def generate_BBs_recursive(code):
    resolve_later = []
    bbs = dict()
    todo = deque([(None, 0)])
    valid_jump_targets = [i for i, c in enumerate(code) if c == 0x5b] # <=== ISSUE HERE
    while True:
        if not todo:
            new_links = False
            for bb in resolve_later:
                _, new_succs = bb.get_succ_addrs_full(valid_jump_targets)
                for _, s in new_succs:
                    new_links = True
                    todo.append((bb.start, s))
            if not new_links:
                break
        p, i = todo.popleft()
        pred = bbs[p] if p is not None else None
    ......
    return bbs.values()
```
It seems you enumerate bytecode to find particularly operation `0x5b` as valid jump targets. 

In my experiment, such enumerate can not handle bytecode correctly. It goes through every single byte of bytes instead of dividing bytecode into two-byte pairs. Moreover, operations take different bits of bytecode as arguments, which is also not being considered is this code.

I wish you could point out my misunderstanding of this code, or fix this issue.

The test bytecode I have used:
`6060604052341561000f57600080fd5b5b6103938061001f6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630129ab27146100545780637cb97b2b146100b2578063a53a1adf146100eb575b600080fd5b341561005f57600080fd5b610094600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610112565b60405180826000191660001916815260200191505060405180910390f35b34156100bd57600080fd5b6100e9600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101ef565b005b34156100f657600080fd5b610110600480803560001916906020019091905050610234565b005b60008060008484604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c01000000000000000000000000028152601401828152602001925050506040518091039020915060008083600019166000191681526020019081526020016000209050848160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508381600101600082825401925050819055508192505b505092915050565b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60003373ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1614151561029257600080fd5b600080836000191660001916815260200190815260200160002090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc82600101549081150290604051600060405180830381858888f19350505050151561031657600080fd5b6000808360001916600019168152602001908152602001600020600080820160006101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055600182016000905550505b50505600a165627a7a7230582063a0f12310e5bf407ccc6cfd750cf57eb9873d23d21ba3b3f7bdaada2a4199790029`

Source code:
```Solidity
pragma solidity ^0.4.0;

contract Test{

    struct Transaction{
        address to;
        uint amount;
    }

    mapping (bytes32 => Transaction) transactions;

    address owner;
    
    function set_owner(address new_owner){
        owner = new_owner;
    }
    
    function new_transaction(address to, uint amount) returns (bytes32){
        bytes32 token = sha3(to, amount);
        Transaction storage t = transactions[token];
        t.to = to;
        t.amount += amount;
        return token;
    }
    
    function approve(bytes32 token){
        require(owner == msg.sender);
        Transaction storage t = transactions[token];
        t.to.transfer(t.amount);
        delete transactions[token];
    }
    
}
````

**Comment by nescio007** [comment]
Hi,
the snippet you mentions does indeed try to identify valid jump targets by looking for `0x5b`, which is the opcode of the `JUMPDEST` instruction.
I am not quite sure what you mean by "two-byte pairs", as EVM instructions do not have a fixed width, and `0x5b` is definitely a one-byte instruction. Do you mean the fact that the contract bytecode is stored as a hexdump, where one contract byte is stored as two ascii-characters?
This is being taken care of by the reading code, which converts the hexadecimal representation from the input file into "actual" bytes (see https://github.com/nescio007/teether/blob/master/bin/extract_contract_code.py#L45-L47):

```python
    with open(sys.argv[1]) as infile:
        inbuffer = infile.read().rstrip()
    code = bytes.fromhex(inbuffer)
```

Further, regarding your example byte, I had no issues extracting the contract code:

```bash
$ cat test.bytecode
6060604052341561000f57600080fd5b5b6103938061001f6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630129ab27146100545780637cb97b2b146100b2578063a53a1adf146100eb575b600080fd5b341561005f57600080fd5b610094600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610112565b60405180826000191660001916815260200191505060405180910390f35b34156100bd57600080fd5b6100e9600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101ef565b005b34156100f657600080fd5b610110600480803560001916906020019091905050610234565b005b60008060008484604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c01000000000000000000000000028152601401828152602001925050506040518091039020915060008083600019166000191681526020019081526020016000209050848160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508381600101600082825401925050819055508192505b505092915050565b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60003373ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1614151561029257600080fd5b600080836000191660001916815260200190815260200160002090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc82600101549081150290604051600060405180830381858888f19350505050151561031657600080fd5b6000808360001916600019168152602001908152602001600020600080820160006101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055600182016000905550505b50505600a165627a7a7230582063a0f12310e5bf407ccc6cfd750cf57eb9873d23d21ba3b3f7bdaada2a4199790029
$ extract_contract_code.py test.bytecode > test.contract         
$ cat test.contract
60606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630129ab27146100545780637cb97b2b146100b2578063a53a1adf146100eb575b600080fd5b341561005f57600080fd5b610094600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610112565b60405180826000191660001916815260200191505060405180910390f35b34156100bd57600080fd5b6100e9600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101ef565b005b34156100f657600080fd5b610110600480803560001916906020019091905050610234565b005b60008060008484604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c01000000000000000000000000028152601401828152602001925050506040518091039020915060008083600019166000191681526020019081526020016000209050848160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508381600101600082825401925050819055508192505b505092915050565b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b60003373ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1614151561029257600080fd5b600080836000191660001916815260200190815260200160002090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc82600101549081150290604051600060405180830381858888f19350505050151561031657600080fd5b6000808360001916600019168152602001908152602001600020600080820160006101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055600182016000905550505b50505600a165627a7a7230582063a0f12310e5bf407ccc6cfd750cf57eb9873d23d21ba3b3f7bdaada2a4199790029
```

Also, the resulting control flow graph looks quite correct to me
```bash
$ plot_cfg.py test.contract > test.dot
INFO:root:Finished all paths
INFO:root:Finished all paths
INFO:root:Finished all paths
$ dot -Tpdf -o test.pdf test.dot
```
[test.pdf](https://github.com/nescio007/teether/files/3741277/test.pdf)

I hope this answers your question,
best regards
Johannes
